### ISSUE TITLE
https://github.com/adafruit/Adafruit_BNO08x

### ISSUE THREAD

**Issue by rhues** [adafruit/Adafruit_CircuitPython_BNO08x#25]
Thanks for the reply, but that is for Arduino and I'm using a Pi Zero W. Is there a solution out there that doesn't use the Arduino headers and is intended for the Pi?

https://github.com/adafruit/Adafruit_BNO08x

_Originally posted by @ladyada in https://github.com/adafruit/Adafruit_CircuitPython_BNO08x/issues/24#issuecomment-831675929_

**Comment by ladyada** [comment]
no
